language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - JYTHON=true
  - JYTHON=false
install: 
  - pip install tox-travis
  - pip install python-coveralls

script:
  - tox
  - coverage run --source ibm_analytics_engine setup.py test
  - coverage report -m

after_success:
  - coveralls

